openapi: 3.0.1
info:
  description: Goal Builder BFF APIs
  title: Goal Builder BFF APIs
  version: "1.0"
  contact: {}
tags: []
servers: []

paths:
  /fws/live/v1/goals:
    get:
      tags:
        - Goals
      operationId: GetGoals
      summary: "Get Goals"
      description: API For getting the Goals
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
        - name: institutionUserId
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: coffeeCanStatus
          in: query
          required: false
          schema:
            type: string
            enum:
              - ACTIVE
              - DEACTIVE
              - COMPLETED
              - CLOSED
              - NON_RECURRING
              - ACTIVE_COMPLETED
              - RECURRING
        - name: coffeeCanId
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: accountId
          in: query
          required: true
          schema:
            type: string
        - name: coffeeCanName
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/CoffeeCan"
        '400':
          $ref: "#/components/responses/400"
        '401':
          $ref: "#/components/responses/401"
        '403':
          $ref: "#/components/responses/403"
        '500':
          $ref: "#/components/responses/500"

    put:
      tags:
        - Goals
      operationId: UpdateGoals
      summary: "Update Goals"
      description: API For Updating the Goals
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
        - name: accountId
          in: query
          required: false
          schema:
            type: string
        - name: notifyReserve
          in: query
          required: false
          schema:
            type: boolean
        - name: reserveLimit
          in: query
          required: false
          schema:
            type: number
            format: double
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoffeeCanUpdateRequest'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/CoffeeCan"
          headers:
            x-correlation-id:
              $ref: "#/components/headers/res-correlationId"
        '400':
          $ref: "#/components/responses/400"
        '401':
          $ref: "#/components/responses/401"
        '403':
          $ref: "#/components/responses/403"
        '500':
          $ref: "#/components/responses/500"

    post:
      tags:
        - Goals
      operationId: CreateGoals
      summary: "Create Goals"
      description: API For Creating the Goals
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoffeeCan'

      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/CoffeeCan"
          headers:
            x-correlation-id:
              $ref: "#/components/headers/res-correlationId"
        '400':
          $ref: "#/components/responses/400"
        '401':
          $ref: "#/components/responses/401"
        '403':
          $ref: "#/components/responses/403"
        '500':
          $ref: "#/components/responses/500"

    delete:
      tags:
        - Goals
      operationId: DeleteGoals
      summary: "Delete Goals"
      description: API For Deleting the Goals
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
        - name: coffeeCanId
          in: query
          required: true
          schema:
            type: integer
            format: int64

      responses:
        '204':
          description: Success
          headers:
            x-correlation-id:
              $ref: "#/components/headers/res-correlationId"
        '400':
          $ref: "#/components/responses/400"
        '401':
          $ref: "#/components/responses/401"
        '403':
          $ref: "#/components/responses/403"
        '500':
          $ref: "#/components/responses/500"

  /fws/live/v1/goals/config:
    get:
      tags:
        - Goal Builder Config
      operationId: GoalBuilderConfig
      summary: "API to get Configs for the Goal Builder"
      description: Get Configs for the Goal Builder
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GBConfigEntity"

  /fws/live/v1/goals/user-account:
    post:
      tags:
        - Update Account
      summary: Change bank account
      description: Change bank account
      operationId: updateAccount
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
        - name: accountId
          in: query
          required: true
          schema:
            type: string
        - name: newAccountId
          in: query
          required: true
          schema:
            type: string
        - name: institutionUserId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountInformation"
        '400':
          $ref: "#/components/responses/400"
        '401':
          $ref: "#/components/responses/401"
        '403':
          $ref: "#/components/responses/403"
        '500':
          $ref: "#/components/responses/500"
  /fws/live/v1/goals/upcoming-transactions:
    get:
      tags:
        - Transactions
      summary: Get list of upcoming(pending) transactions
      description: Returns list of upcoming(pending) transactions
      operationId: getUpcomingTransactions
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
        - name: institutionUserId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/TransactionsResponse"
        '401':
          $ref: "#/components/responses/401"
        '500':
          $ref: "#/components/responses/500"

  /fws/live/v1/goals/transactions:
    get:
      tags:
        - Transactions
      summary: Get list of pending and completed transactions
      description: Returns list of pending and completed transactions
      operationId: getTransactions
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
        - name: institutionUserId
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: coffeeCanIdList
          in: query
          required: false
          schema:
            type: array
            items:
              type: integer
              format: int64
        - name: fromDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: toDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsResponse'
        '400':
          description: Invalid date range
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BFFError"
              example:
                statusCode: 400
                error: Invalid date range
                message: Client executed a bad request
                details: "/query/date must have correct format 'startEnd/endDate' "
                displayMessage: Client executed a bad request
        '401':
          $ref: "#/components/responses/401"
        '500':
          $ref: "#/components/responses/500"

  /fws/live/v1/goals/goalAccount:
    get:
      tags:
        - Goal Details
      summary: Returns user bank account and Goal savings
      description: Returns user bank account and Goal savings
      operationId: getInstitutionUserAccountDetail
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
        - name: institutionUserId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountInformation'
        '400':
          $ref: "#/components/responses/400"
        '401':
          $ref: "#/components/responses/401"
        '500':
          $ref: "#/components/responses/500"
  /fws/live/v1/goals/fund-types:
    get:
      tags:
        - Funds
      operationId: getFundTypes
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object

  /fws/live/v1/goals/deposit-allocation:
    get:
      tags:
        - Deposit Allocation
      operationId: getDepositAllocationForAllCans
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
        - name: institutionUserId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepositAllocationSumResponse'
  /fws/live/v1/goals/goals-account:
    get:
      tags:
        - Goals & Account Details
      operationId: getCoffeeCanListAndAccountDetails
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
        - name: institutionUserId
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: coffeeCanStatus
          in: query
          required: false
          schema:
            type: string
            enum:
              - ACTIVE
              - DEACTIVE
              - COMPLETED
              - CLOSED
              - NON_RECURRING
              - ACTIVE_COMPLETED
              - RECURRING
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /fws/live/v1/goals/core-accounts:
    get:
      tags:
        - Get Accounts
      summary: Get eligible bank accounts
      description: Returns eligible bank accounts
      operationId: getBankAccounts
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
        - name: listAccount
          in: query
          required: true
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountsResponse'
        '400':
          $ref: "#/components/responses/400"
        '401':
          $ref: "#/components/responses/401"
        '500':
          $ref: "#/components/responses/500"
  /fws/live/v1/goals/delete-upcoming:
    delete:
      tags:
        - Delete Recurring Transfers
      summary: Deletes(skip) upcoming execution of recurring transfer job
      description: Deletes(skip) upcoming execution of recurring transfer job
      operationId: deleteUpcomingJob
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
        - name: coffeeCanId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Resource Deleted
          headers:
            x-correlation-id:
              $ref: "#/components/headers/res-correlationId"

        '400':
          $ref: "#/components/responses/400"
        '401':
          $ref: "#/components/responses/401"
        '500':
          $ref: "#/components/responses/500"

  /fws/live/v1/goals/complete-notification:
    get:
      tags:
        - Toaster Notification
      operationId: getToasterNotification
      parameters:
        - name: isRead
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
    put:
      tags:
        - Toaster Notification
      operationId: updateToasterNotification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompleteCanUpdateRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
  /fws/live/v1/goals/viewGLBEndUserFullList:
    post:
      tags:
        - AP-SupportDashboard-Extension
      operationId: viewGLBEndUserFullList
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfo'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
  /fws/live/v1/goals/findGLBEndUserStatus:
    post:
      tags:
        - AP-SupportDashboard-Extension
      operationId: findGLBEndUserStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfo'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object

# ------------------- Components ----------------

components:
  securitySchemes:
    auth:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    GBConfigEntity:
      type: object
      properties:
        primaryUser:
          type: boolean
        userType:
          type: string
          description: User Type (PRIMARY or ENTITLED)
          example: PRIMARY or ENTITLED
      required:
        - primaryUser
        - userType
    CompleteCanUpdateRequest:
      type: object
      properties:
        notificationId:
          type: integer
          format: int64
        coffeeCanId:
          type: integer
          format: int64
        isRead:
          type: boolean
    CoffeeCan:
      type: object
      properties:
        coffeeCanId:
          type: integer
          format: int64
        getcIdTo:
          type: integer
          format: int64
        accountId:
          type: string
        institutionUserId:
          type: integer
          format: int64
        fundTypeId:
          type: integer
          format: int64
        coffeeCanName:
          type: string
        coffeeCanType:
          type: string
          enum:
            - PREDEFINED
            - PREDEFINED_NOT
        coffeeCanStatus:
          type: string
          enum:
            - ACTIVE
            - DEACTIVE
            - COMPLETED
            - CLOSED
            - NON_RECURRING
            - ACTIVE_COMPLETED
            - RECURRING
        targetAmount:
          type: number
          format: double
        totalSavingAmount:
          type: number
          format: double
        monthlyAmount:
          type: number
          format: double
        depositAllocation:
          type: number
          format: double
        goalStartDate:
          type: string
          format: date
        goalEndDate:
          type: string
          format: date
        recurringAction:
          type: string
          enum:
            - Create
            - Update
            - Delete
        recurringDetail:
          $ref: '#/components/schemas/RecurringDetail'
        transactionType:
          type: string
        transactionAmount:
          type: number
          format: double
        activeDeactiveAmount:
          type: number
          format: double
        transactionList:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
        pendingList:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
        nickName:
          type: string
        memo:
          type: string
        completionDate:
          type: string
          format: date-time
        toasterMessage:
          type: string
        iconUrl:
          type: string
        isRead:
          type: boolean
    CoffeeCanUpdateRequest:
      type: object
      properties:
        coffeeCans:
          type: array
          items:
            $ref: '#/components/schemas/CoffeeCan'
    RecurringDetail:
      type: object
      properties:
        recAmount:
          type: number
          format: double
        recStartDate:
          type: string
          format: date
        frequencyType:
          type: string
        recEndType:
          type: string
        recEndDate:
          type: string
          format: date
        numberOfTransfer:
          type: integer
          format: int32
        scheduleDetails:
          type: array
          items:
            $ref: '#/components/schemas/ScheduleDetail'
    ScheduleDetail:
      type: object
      properties:
        recurringId:
          type: integer
          format: int64
        timeOfDay:
          type: string
          format: date-time
        interval:
          type: integer
          format: int32
        day:
          type: integer
          format: int32
    Transaction:
      type: object
      properties:
        transactionId:
          type: integer
          format: int64
        coffeeCanId:
          type: integer
          format: int64
        transactionAmount:
          type: number
          format: double
        transactionDatetime:
          type: string
          format: date-time
        transactionType:
          type: string
        transactionName:
          type: string
        totalSavingAmount:
          type: number
          format: double
        frequencyType:
          type: string
        transactionMemo:
          type: string
        canToCan:
          type: string
        transactionDescription:
          type: string
        depositAmount:
          type: number
          format: double
        accountNumber:
          type: string
        accountName:
          type: string
        coffeeCanName:
          type: string
    MessageToasterUpdateRequest:
      type: object
      properties:
        ids:
          type: array
          items:
            type: integer
            format: int64
    UserInfo:
      type: object
      properties:
        fiId:
          type: string
        userGuid:
          type: string
        userMemberId:
          type: string
    TransactionsResponse:
      type: object
      properties:
        pendingTransactionsList:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
        transactionsList:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    AccountInformation:
      type: object
      properties:
        institutionUserId:
          type: integer
          format: int64
        accountBalance:
          type: number
          format: double
        remainingBalance:
          type: number
          format: double
        nickName:
          type: string
        isBalanceAdjusted:
          type: boolean
        isNotifyReserve:
          type: boolean
        reserveLimit:
          type: number
          format: double
        isIncompleteDistribution:
          type: boolean
        displayAccountNumber:
          type: string
        accountType:
          type: integer
        isAccountAvailable:
          type: boolean
    DepositAllocationSumResponse:
      type: object
      properties:
        sum:
          type: number
          format: double
        message:
          type: string
    AccountsResponse:
      type: object
      properties:
        accountId:
          type: string
        description:
          type: string
        nickName:
          type: string
        displayAccountNumber:
          type: string
        availableBalance:
          type: number
        displayCardNumber:
          type: string

    error:
      type: "object"
      properties:
        code:
          type: "string"
          description: "The error code"
          example: "GB-400-1001"
        message:
          type: "string"
          description: "The error message"
          example: "/query/goals must have required property 'accountId' "
    errors:
      type: "object"
      properties:
        errors:
          type: "array"
          items:
            $ref: "#/components/schemas/error"
    BFFError:
      type: object
      anyOf:
        - type: object
          properties:
            statusCode:
              type: integer
              example: 400
            error:
              type: string
              example: ClientErrorException
            message:
              type: string
              example: Client executed a bad request
            details:
              $ref: "#/components/schemas/errors"
            displayMessage:
              type: string
              example: Client executed a bad request
            timestamp:
              type: string
              example: "2025-06-23T16:07:16.109Z"
            path:
              type: string
              example: "/v1/fws"
        - type: object
          properties:
            statusCode:
              type: integer
              example: 400
            error:
              type: string
              example: ClientErrorException
            message:
              type: string
              example: Client executed a bad request
            details:
              type: string
              example: "/query/goals must have required property 'accountId' "
            displayMessage:
              type: string
              example: Client executed a bad request
            timestamp:
              type: string
              example: "2025-05-23T16:07:16.109Z"
            path:
              type: string
              example: "/v1/fws?accountId=kP8snK0hBwOLEprxJbgsJD8WP-bOIsDSeqnMi1QWvdo"

  parameters:
    correlationId:
      name: x-correlation-id
      in: header
      example: 07ae5002-4d4d-46d9-a6c6-bee9f9b29722
      schema:
        type: string
    authorization:
      name: Authorization
      in: header
      description: Signed JWT carrying user data
      required: false
      schema:
        type: string
        default: Bearer <JWT>

  headers:
    req-correlationId:
      description: Identifier for request
      required: false
      schema:
        type: string
        format: uuid
        default: d6d6aca7-8ac6-4339-8470-f4a0acc781b3
    res-correlationId:
      description: Identifier for response
      required: false
      schema:
        type: string
        format: uuid
        default: d6d6aca7-8ac6-4339-8470-f4a0acc781b3

  responses:
    400:
      description: "Bad Request"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BFFError"
          example:
            statusCode: 400
            error: ValidationException
            message: Client executed a bad request
            details: "/query/goals must have required property 'accountId' "
            displayMessage: Client executed a bad request
    401:
      description: "Invalid Session"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BFFError"
          example:
            statusCode: 401
            error: InvalidSessionException
            message: Unauthorized Invalid Session
            details: Invalid Session
    403:
      description: "Invalid JWT"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BFFError"
          example:
            statusCode: 403
            error: InvalidJWTException
            message: JWT is invalid
            details: Invalid Authorization
    500:
      description: "Internal Server Error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BFFError"
          example:
            statusCode: 500
            error: ServerErrorException
            message: Server encountered a System Error
            details: Internal Server Error
            displayMessage: Server executed a system error